name: Trivy Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  trivy-scan:
    name: Run Trivy Vulnerability Scanner
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Trivy
      run: |
       sudo apt-get update
       curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin


    - name: Run Trivy and Save JSON Report
      run: |
        trivy fs . --format json --output trivy-report.json --severity HIGH,CRITICAL --exit-code 1



